[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://backend-doarcuidar.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
