name: CI DoarCuidar

on:
  push:
    branches: ["developer", "main"]
  pull_request:
    branches: ["developer", "main"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Validar lint
        run: npm run lint

      - name: Rodar testes
        run: npm run test

      - name: Rodar build
        run: npm run build
