name: CI DoarCuidar

on:
  push:
    branches: [ "developer", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Rodar testes
        run: npm run test || echo "Sem testes ainda"